version: '3.3'
services:
  db:
    image: mysql:8.0
    platform: linux/x86_64
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      
      MYSQL_USER: 'user'
 
      MYSQL_PASSWORD: 'password'
    
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    expose:
      - '3307'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:

# docker-compose up -d